"""AML Transaction Monitoring — investigator dashboard entry point.

Run with ``streamlit run ui/app.py``. The remaining pages in
``ui/pages/`` are auto-discovered by Streamlit's multipage navigation
based on filename prefix (``1_``, ``2_``, ...) and rendered in the
sidebar in that order.

This landing page surfaces the operational summary an investigator
needs at shift start: current API health, open alert counts by tier,
and the resolution stats from the most recent processing cycle.
"""

from __future__ import annotations

import streamlit as st

from ui.components.api_client import APIError, get_api_client


def render_landing() -> None:
    """Render the landing page with health and operational KPIs."""
    st.set_page_config(
        page_title="AML Transaction Monitoring",
        page_icon="🛡️",
        layout="wide",
        initial_sidebar_state="expanded",
    )

    st.title("AML Transaction Monitoring")
    st.markdown(
        "_Hybrid anomaly + supervised scoring · Claude-powered case triage · "
        "Full investigator feedback loop_"
    )
    st.divider()

    client = get_api_client()

    # ----- Service health row -------------------------------------------
    with st.container():
        try:
            health = client.get_health()
        except APIError as exc:
            st.error(f"API unreachable — {exc}")
            return
        except Exception as exc:
            st.error(f"Failed to reach scoring service: {exc}")
            return

        status_label = str(health.get("status", "unknown")).upper()
        if status_label == "OK":
            st.success(f"Service status: {status_label}")
        else:
            st.warning(f"Service status: {status_label}")

        info_cols = st.columns(4)
        info_cols[0].metric("Service version", health.get("service_version", "—"))
        info_cols[1].metric(
            "Model loaded",
            "Yes" if health.get("model_loaded") else "No",
        )
        info_cols[2].metric(
            "Decision threshold",
            f"{health.get('decision_threshold') or 0:.4f}"
            if health.get("decision_threshold") is not None
            else "—",
        )
        info_cols[3].metric(
            "LLM configured",
            "Yes" if health.get("llm_configured") else "No",
        )

    st.divider()

    # ----- Alert volume tiles -------------------------------------------
    st.subheader("Current alert queue")

    # The landing page surfaces just-the-counts so the operator can
    # decide which page to drill into. The actual alert listing lives
    # on the queue page. We fetch counts via the /alerts endpoint with
    # ``limit=0`` to avoid moving the full alert payloads over the
    # wire on every dashboard refresh.
    queue_cols = st.columns(5)
    statuses = [
        ("open", "Open"),
        ("in_review", "In Review"),
        ("cleared", "Cleared (24h)"),
        ("escalated", "Escalated (24h)"),
        ("sar_filed", "SAR Filed (24h)"),
    ]
    for col, (status_key, label) in zip(queue_cols, statuses):
        try:
            result = client.list_alerts(status=status_key, limit=1)
            count = int(result.get("total_matching", 0))
        except Exception:
            count = 0
        col.metric(label, count)

    st.caption(
        "Counts refresh on each page render. Use the **Alert Queue** page in the "
        "sidebar to filter and act on individual alerts."
    )

    st.divider()

    # ----- Reference panel ----------------------------------------------
    with st.expander("About this system"):
        st.markdown(
            """
            This dashboard is the investigator-facing surface for an AML
            monitoring service. The scoring engine combines an Isolation Forest
            anomaly head with a gradient-boosted classifier (XGBoost / LightGBM /
            CatBoost ensemble), tuned on the IBM AML HI-Small benchmark. Every
            alert ships with an evidence-bound case narrative generated by
            Claude — every claim in the narrative cites a specific transaction
            or feature value from the evidence bundle.

            **Pages:**
            - **Alert Queue** — filtered listing of all alerts
            - **Alert Detail** — full alert with narrative, citations, and
              investigator feedback capture
            - **Drift Monitor** — Population Stability Index for features and
              predictions over time
            - **Fairness Audit** — segment-level demographic parity, equal
              opportunity, and FPR parity
            """
        )


if __name__ == "__main__":
    render_landing()
else:
    # Streamlit imports the module as ``__name__ != "__main__"`` when it
    # discovers the page. The render function runs unconditionally here
    # because Streamlit's page-rendering model relies on top-level
    # execution rather than an explicit entry call.
    render_landing()
